# Generated by Django 5.0.4 on 2026-01-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0002_alter_adifupload_file_size_alter_adifupload_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qso',
            name='his_qth',
            field=models.CharField(blank=True, help_text='QTH корреспондента', max_length=100),
        ),
        migrations.AddField(
            model_name='qso',
            name='notes',
            field=models.TextField(blank=True, help_text='Примечания'),
        ),
    ]
