# Generated by Django 5.0.4 on 2026-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0004_alter_qso_his_gridsquare_alter_qso_his_qth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='rst_received',
            field=models.CharField(blank=True, help_text='RST принятый', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qso',
            name='rst_sent',
            field=models.CharField(blank=True, help_text='RST переданный', max_length=10, null=True),
        ),
    ]
