# Generated by Django 5.0.4 on 2026-01-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0006_rename_rst_received_qso_rst_rcvd_remove_qso_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioprofile',
            name='antenna_height',
        ),
        migrations.RemoveField(
            model_name='radioprofile',
            name='antenna_type',
        ),
        migrations.RemoveField(
            model_name='radioprofile',
            name='license_class',
        ),
        migrations.RemoveField(
            model_name='radioprofile',
            name='power_output',
        ),
        migrations.RemoveField(
            model_name='radioprofile',
            name='radio_model',
        ),
    ]
