# Generated by Django 5.0.4 on 2026-01-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0007_remove_radioprofile_antenna_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprofile',
            name='my_callsigns',
            field=models.TextField(blank=True, help_text='Мои позывные (бывшие, действующие, спецпозывные, позывные с дробями) - через запятую'),
        ),
    ]
