# Generated by Django 5.0.4 on 2026-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0008_add_my_callsigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioprofile',
            name='my_callsigns',
            field=models.JSONField(blank=True, default=list, help_text='Мои позывные в формате JSON'),
        ),
    ]
