# Generated by Django 5.0.4 on 2026-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0009_change_my_callsigns_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=100),
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=100),
        ),
    ]
