# Generated by Django 5.0.4 on 2026-01-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0010_add_name_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radioprofile',
            options={'verbose_name': 'Регистрация пользователей', 'verbose_name_plural': 'Регистрация пользователей'},
        ),
        migrations.AddField(
            model_name='qso',
            name='adif_upload',
            field=models.ForeignKey(blank=True, help_text='Загрузка ADIF, из которой создана запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qsos', to='tlog.adifupload'),
        ),
    ]
