# Generated by Django 5.0.4 on 2026-01-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0011_add_adif_upload_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='adif_upload',
            field=models.ForeignKey(blank=True, help_text='Связанная загрузка ADIF файла', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qso_records', to='tlog.adifupload'),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
