# Generated by Django 5.0.4 on 2026-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0012_alter_qso_adif_upload_alter_radioprofile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qso',
            old_name='his_gridsquare',
            new_name='gridsquare',
        ),
        migrations.RenameField(
            model_name='qso',
            old_name='lotw_qsl',
            new_name='lotw',
        ),
        migrations.AddField(
            model_name='qso',
            name='cqz',
            field=models.IntegerField(blank=True, help_text='CQ зона', null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='ituz',
            field=models.IntegerField(blank=True, help_text='ITU зона', null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='prop_mode',
            field=models.CharField(blank=True, help_text='Режим распространения', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='r150s',
            field=models.CharField(blank=True, help_text='R150S', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='sat_name',
            field=models.CharField(blank=True, help_text='Название спутника', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='state',
            field=models.CharField(blank=True, help_text='Штат/регион', max_length=10, null=True),
        ),
    ]
