# Generated by Django 5.0.4 on 2026-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0013_update_qso_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='qso',
            name='continent',
            field=models.CharField(blank=True, help_text='Континент', max_length=2, null=True),
        ),
    ]
