# Generated by Django 5.0.4 on 2026-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0014_add_continent_to_qso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='r150s',
            field=models.CharField(blank=True, help_text='R150S', max_length=100, null=True),
        ),
    ]
