# Generated by Django 5.0.4 on 2026-01-17 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0015_increase_r150s_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(help_text='Позывной лога', max_length=20)),
                ('author_callsign', models.CharField(help_text='Позывной автора', max_length=20)),
                ('message', models.TextField(help_text='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['callsign', '-created_at'], name='logbook_comment_callsign_idx')],
            },
        ),
    ]
