# Generated by Django 5.0.4 on 2026-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0016_logbookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Дата блокировки', null=True),
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='blocked_reason',
            field=models.TextField(blank=True, default='', help_text='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Заблокировать доступ к личному кабинету'),
        ),
    ]
