# Generated by Django 5.0.4 on 2026-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0017_radioprofile_blocked_at_radioprofile_blocked_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qso',
            name='his_qth',
        ),
        migrations.RemoveField(
            model_name='qso',
            name='state',
        ),
        migrations.AddField(
            model_name='qso',
            name='dxcc',
            field=models.CharField(blank=True, help_text='DXCC', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='ru_region',
            field=models.CharField(blank=True, help_text='RU область/регион', max_length=100, null=True),
        ),
    ]
