# Generated by Django 4.2.7 on 2026-01-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0018_remove_qso_his_qth_remove_qso_state_qso_dxcc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogbookComment',
        ),
    ]
