# Generated by Django 4.2.7 on 2026-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0019_del_logbook_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['my_callsign'], name='qso_my_callsign_idx'),
        ),
    ]
