# Generated by Django 5.2 on 2026-01-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0002_radioprofile_first_name_last_name'),
        ('tlog', '0021_chat_message'),
    ]

    operations = [
    ]
