# Generated by Django 5.2 on 2026-01-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0022_merge_20260121_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
    ]
