# Generated by Django 5.2 on 2026-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0023_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprofile',
            name='lotw_chk_pass',
            field=models.BooleanField(default=False, help_text='Проверен ли логин и пароль от LoTW'),
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='lotw_password',
            field=models.CharField(blank=True, help_text='Пароль от LoTW', max_length=100),
        ),
        migrations.AddField(
            model_name='radioprofile',
            name='lotw_user',
            field=models.CharField(blank=True, help_text='Логин от LoTW', max_length=50),
        ),
    ]
