# Generated by Django 5.0.4 on 2026-01-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0024_radioprofile_lotw_chk_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprofile',
            name='lotw_lastsync',
            field=models.DateTimeField(blank=True, help_text='Время последней синхронизации с LoTW', null=True),
        ),
    ]
