# Generated by Django 5.2 on 2026-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0025_radioprofile_lotw_lastsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='qso',
            name='app_lotw_rxqsl',
            field=models.DateTimeField(blank=True, help_text='Дата и время получения подтверждения LoTW', null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='iota',
            field=models.CharField(blank=True, help_text='IOTA номер острова', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qso',
            name='vucc_grids',
            field=models.CharField(blank=True, help_text='VUCC Grids (несколько локаторов)', max_length=100, null=True),
        ),
    ]
