# Generated by Django 5.2 on 2026-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0026_add_lotw_vucc_iota_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='dxcc',
            field=models.CharField(blank=True, help_text='DXCC', max_length=100, null=True),
        ),
    ]
