# Generated by Django 5.2 on 2026-02-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0027_alter_qso_dxcc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qso',
            old_name='ru_region',
            new_name='state',
        ),
    ]
