# Generated by Django 5.2 on 2026-02-16 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0030_add_cosmos_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='state',
            field=models.CharField(blank=True, help_text='Регион/штат', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'lotw'], name='qso_user_lotw_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'sat_name'], name='qso_user_sat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'r150s'], name='qso_user_r150s_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'dxcc'], name='qso_user_dxcc_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'state'], name='qso_user_state_idx'),
        ),
    ]
