# Generated by Django 5.2 on 2026-02-16 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0031_add_user_achievements_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['cqz'], name='qso_cqz_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['ituz'], name='qso_ituz_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['iota'], name='qso_iota_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['vucc_grids'], name='qso_vucc_grids_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'cqz'], name='qso_user_cqz_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'ituz'], name='qso_user_ituz_idx'),
        ),
        migrations.AddIndex(
            model_name='qso',
            index=models.Index(fields=['user', 'iota'], name='qso_user_iota_idx'),
        ),
    ]
