# Generated by Django 5.2 on 2026-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0032_add_rating_page_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='mode',
            field=models.CharField(choices=[('SSB', 'SSB'), ('CW', 'CW'), ('FM', 'FM'), ('AM', 'AM'), ('RTTY', 'RTTY'), ('PSK31', 'PSK31'), ('PSK63', 'PSK63'), ('FT8', 'FT8'), ('FT4', 'FT4'), ('FT2', 'FT2'), ('JT65', 'JT65'), ('JT9', 'JT9'), ('SSTV', 'SSTV'), ('JS8', 'JS8'), ('MSK144', 'MSK144')], max_length=20),
        ),
    ]
