# Generated by Django 5.0.4 on 2026-01-15 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adifupload',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='adifupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='antenna_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='antenna_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='callsign',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='power_output',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='radioprofile',
            name='radio_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
