# Generated by Django 5.0.4 on 2026-01-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_qso_his_qth_qso_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qso',
            name='his_gridsquare',
            field=models.CharField(blank=True, help_text='QTH локатор корреспондента', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qso',
            name='his_qth',
            field=models.CharField(blank=True, help_text='QTH корреспондента', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qso',
            name='my_gridsquare',
            field=models.CharField(blank=True, help_text='Мой QTH локатор', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qso',
            name='notes',
            field=models.TextField(blank=True, help_text='Примечания', null=True),
        ),
    ]
