# Generated by Django 5.0.4 on 2026-01-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_qso_rst_received_alter_qso_rst_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qso',
            old_name='rst_received',
            new_name='rst_rcvd',
        ),
        migrations.RemoveField(
            model_name='qso',
            name='notes',
        ),
        migrations.AddField(
            model_name='qso',
            name='lotw_qsl',
            field=models.CharField(blank=True, default='N', help_text='Подтверждение LoTW', max_length=1),
        ),
        migrations.AddField(
            model_name='qso',
            name='paper_qsl',
            field=models.CharField(blank=True, default='N', help_text='Бумажная QSL', max_length=1),
        ),
    ]
